CREATE TABLE [tblInstalls4] (
  [lngID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [strCustomer] VARCHAR (255),
  [strAddressStreet] VARCHAR (255),
  [strAddressCity] VARCHAR (255),
  [strAddressState] VARCHAR (2),
  [strAddressZIP] VARCHAR (5),
  [strSalesRep] VARCHAR (32),
  [strInstallStatus] VARCHAR (255),
  [dtmDateReceived] DATETIME ,
  [strContactName] VARCHAR (255),
  [strContactPhone] VARCHAR (14),
  [strContactEmail] VARCHAR (255),
  [strITContactName] VARCHAR (255),
  [strITContactPhone] VARCHAR (14),
  [strITContactEmail] VARCHAR (255),
  [memDeliveryNotes] LONGTEXT ,
  [ysnFMAuditCreated] BIT ,
  [ysnStairsRequired] BIT ,
  [ysnElevatorRequired] BIT ,
  [ysnDockDelivery] BIT ,
  [memDeploymentInfo] LONGTEXT ,
  [memNetworkInfo] LONGTEXT ,
  [memSpecialInstructions] LONGTEXT ,
  [memNotes] LONGTEXT ,
  [dtmInstallScheduled] VARCHAR (255),
  [dtmDepartureTime] VARCHAR (255),
  [strDepartureFrom] VARCHAR (255),
  [attAttachments] VARCHAR ,
  [memPostInstallNotes] LONGTEXT ,
  [dtmDeliveryDate] DATETIME ,
  [strDeliveryMethod] VARCHAR (255)
)
